[tool.poetry]
name = "pyevt"
version = "0.2.1"
description = "API for EVT-2 USB devices"
authors = [
	"Martin Stokroos <m.stokroos@rug.nl>",
    "Mark M. Span <m.m.span@rug.nl>"
]
maintainers = [
]
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["evt", "api", "usb", "hid", "psychology", "response-box"]
homepage = "https://github.com/BSS-Research-Support/pyevt"
documentation = "https://github.com/BSS-Research-Support/pyevt"

[tool.poetry.urls]
Repository = "https://github.com/BSS-Research-Support/pyevt"

[tool.poetry.dependencies]
python = "^3.8"
hidapi = "~0.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

